### ISSUE TITLE
Releases 4.3.2, 4.4.0 and 4.4.1 missing

### ISSUE THREAD

**Issue by elkangaroo** [psalm/phar#6]
Could you please add the missing releases? 
Last release here is 4.3.1, but on vimeo/psalm it is 4.4.1 (see https://github.com/vimeo/psalm/releases).

**Comment by mitelg** [comment]
+1

please @muglug could you update the latest versions :blush:

**Comment by muglug** [comment]
I've added 4.5.1, and have fixed the automatic tagging for the future, but you'll have to do without the intermediary releases I'm afraid

**Comment by mitelg** [comment]
thank you very much 👍👍
